"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Difficulty, SigEvent, spotsLeft } from "@/lib/events";
import { formatEventDateTime, getEventReadiness, isFillingFast } from "@/lib/event-view";

const levels: Difficulty[] = ["beginner", "intermediate", "advanced"];

export function MemberEventHub({ events }: { events: SigEvent[] }) {
  const [tracks, setTracks] = useState<string[]>([]);
  const [difficulties, setDifficulties] = useState<Difficulty[]>([]);
  const allTracks = useMemo(() => [...new Set(events.map((event) => event.track))], [events]);
  const filtered = events.filter((event) => (tracks.length === 0 || tracks.includes(event.track)) && (difficulties.length === 0 || difficulties.includes(event.difficulty)));
  const [featured, ...remaining] = filtered;
  const fillingFast = events.filter(isFillingFast).slice(0, 3);
  const clear = () => { setTracks([]); setDifficulties([]); };
  const toggleTrack = (track: string) => setTracks((current) => current.includes(track) ? current.filter((item) => item !== track) : [...current, track]);
  const toggleLevel = (level: Difficulty) => setDifficulties((current) => current.includes(level) ? current.filter((item) => item !== level) : [...current, level]);

  return <div className="flex flex-col gap-16">
    {featured ? <FeaturedEvent event={featured} /> : <NoEvents onClear={clear} />}
    <section aria-labelledby="browse-events" className="flex flex-col gap-6">
      <div className="flex flex-col gap-3 border-b-2 border-stone-900 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="browse-events" className="font-display text-4xl font-bold tracking-tight text-stone-950">Upcoming programme</h2></div>{(tracks.length > 0 || difficulties.length > 0) && <button onClick={clear} className="w-fit text-sm font-semibold text-blue-700 underline underline-offset-4">Clear filters</button>}</div>
      <div className="grid gap-x-10 gap-y-4 border-b border-stone-300 pb-5 sm:grid-cols-2"><FilterGroup label="Browse by event type" values={allTracks} selected={tracks} onToggle={toggleTrack} /><FilterGroup label="Browse by experience" values={levels} selected={difficulties} onToggle={toggleLevel} /></div>
      {remaining.length > 0 && <div>{remaining.map((event) => <ProgrammeRow key={event.id} event={event} />)}</div>}
    </section>
    {fillingFast.length > 0 && <section aria-labelledby="filling-fast" className="rounded-3xl bg-blue-950 px-6 py-8 text-white sm:px-9"><div className="mb-6"><p className="text-sm font-semibold text-blue-200">Popular right now</p><h2 id="filling-fast" className="font-display text-3xl font-bold">Filling fast</h2><p className="mt-2 max-w-lg text-sm text-blue-100">These sessions have limited places remaining—register when you are ready.</p></div><div className="grid gap-3 md:grid-cols-3">{fillingFast.map((event) => <Link key={event.id} href={`/events/${event.id}`} className="rounded-2xl bg-white/10 p-4 transition hover:bg-white/15"><p className="font-semibold">{event.title}</p><p className="mt-2 text-sm text-blue-100">{spotsLeft(event)} places left · {formatEventDateTime(event.dateISO)}</p></Link>)}</div></section>}
  </div>;
}

function FilterGroup<T extends string>({ label, values, selected, onToggle }: { label: string; values: readonly T[]; selected: T[]; onToggle: (value: T) => void }) { return <div><p className="mb-2 text-sm font-semibold text-stone-800">{label}</p><div className="flex flex-wrap gap-x-5 gap-y-2">{values.map((value) => <button key={value} onClick={() => onToggle(value)} aria-pressed={selected.includes(value)} className={`border-b-2 pb-1 text-sm font-semibold transition ${selected.includes(value) ? "border-blue-700 text-blue-700" : "border-transparent text-stone-600 hover:border-stone-400 hover:text-stone-950"}`}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div></div>; }

function FeaturedEvent({ event }: { event: SigEvent }) { const readiness = getEventReadiness(event); const action = event.status === "waitlist" ? "Join waitlist" : event.status === "closed" ? "View details" : "Register now"; return <section className="grid border-y-2 border-stone-900 bg-[#f8c94f] md:grid-cols-[1.45fr_0.55fr]"><div className="p-7 sm:p-12"><p className="mb-8 text-sm font-bold uppercase tracking-[0.18em] text-stone-900">Next session</p><h1 className="max-w-2xl font-display text-5xl font-bold leading-[0.92] tracking-tight text-stone-950 sm:text-7xl">{event.title}</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-stone-800">{event.description}</p><div className="mt-9 flex flex-wrap gap-5"><Link href={`/events/${event.id}`} className="bg-stone-950 px-6 py-3 text-sm font-bold text-white hover:bg-blue-800">{action}</Link><Link href={`/events/${event.id}`} className="border-b-2 border-stone-900 pb-1 text-sm font-bold text-stone-950">Full event details</Link></div></div><aside className="border-t-2 border-stone-900 bg-[#fffcf7] p-7 md:border-l-2 md:border-t-0 sm:p-10"><h2 className="font-display text-2xl font-bold text-stone-950">The essentials</h2><dl className="mt-6 space-y-5 text-sm"><Fact label="When" value={formatEventDateTime(event.dateISO)} /><Fact label="Where" value={event.location} /><Fact label="Good for" value={readiness.audience} /><Fact label="Bring" value={readiness.preparation} /><Fact label="Availability" value={readiness.availability} /></dl></aside></section>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="font-semibold text-stone-950">{label}</dt><dd className="mt-1 leading-relaxed text-stone-600">{value}</dd></div>; }
function ProgrammeRow({ event }: { event: SigEvent }) { const readiness = getEventReadiness(event); return <article className="grid gap-4 border-t-2 border-stone-900 py-6 md:grid-cols-[6rem_1fr_auto] md:items-start"><div className="font-display text-2xl font-bold leading-none text-blue-800">{new Date(event.dateISO).toLocaleDateString("en-SG", { day: "2-digit", month: "short" })}</div><div><p className="text-sm font-semibold text-blue-700">{event.track} · {event.difficulty}</p><h3 className="mt-1 font-display text-3xl font-bold tracking-tight text-stone-950">{event.title}</h3><p className="mt-2 max-w-2xl text-sm leading-relaxed text-stone-600">{event.location} · {readiness.audience} · {readiness.preparation}</p></div><Link href={`/events/${event.id}`} className="w-fit border-b-2 border-blue-700 pb-1 text-sm font-bold text-blue-700">{event.status === "waitlist" ? "Join waitlist" : event.status === "closed" ? "Details" : "Register"}</Link></article>; }
function EventCard({ event }: { event: SigEvent }) { const readiness = getEventReadiness(event); return <article className="flex flex-col rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm font-medium text-blue-700">{event.track} · {event.difficulty}</p><h3 className="mt-3 font-display text-2xl font-bold tracking-tight text-stone-950">{event.title}</h3><p className="mt-3 text-sm leading-relaxed text-stone-600">{event.description}</p><div className="mt-5 space-y-2 text-sm text-stone-700"><p>{formatEventDateTime(event.dateISO)}</p><p>{event.location}</p><p>{readiness.audience}</p></div><Link href={`/events/${event.id}`} className="mt-6 text-sm font-semibold text-blue-700 underline underline-offset-4">{event.status === "waitlist" ? "Join waitlist" : event.status === "closed" ? "View details" : "Register"}</Link></article>; }
function NoEvents({ onClear }: { onClear: () => void }) { return <section className="rounded-3xl bg-stone-100 p-10 text-center"><h2 className="font-display text-3xl font-bold text-stone-950">Nothing matches both filters</h2><p className="mt-3 text-stone-600">Try broadening your choices to see more upcoming sessions.</p><button onClick={onClear} className="mt-6 rounded-full bg-blue-700 px-5 py-3 text-sm font-semibold text-white">Clear filters</button></section>; }
