import Link from "next/link";
import { SigEvent, spotsLeft } from "@/lib/events";
import { formatEventDateTime, isFillingFast } from "@/lib/event-view";

export function OperationsSummary({ events }: { events: SigEvent[] }) {
  const next = [...events].filter((event) => event.status !== "closed").sort((a, b) => new Date(a.dateISO).getTime() - new Date(b.dateISO).getTime())[0];
  const waitlisted = events.reduce((total, event) => total + event.waitlisted, 0);
  const risks = events.filter(isFillingFast);
  return <div className="flex flex-col gap-8"><div><p className="text-sm font-semibold text-blue-700">EXCO workspace</p><h1 className="mt-1 font-display text-4xl font-bold tracking-tight text-slate-950">Club operations</h1><p className="mt-3 max-w-2xl text-slate-600">A practical view of what needs attention before your next session.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Next event" value={next?.title ?? "No event scheduled"} note={next ? formatEventDateTime(next.dateISO) : ""} /><Metric label="Capacity risks" value={`${risks.length}`} note={risks.length ? risks.map((event) => event.title).join(", ") : "No events are close to full"} /><Metric label="People on waitlists" value={`${waitlisted}`} note="Review changes before the next event" /></div>{next && <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-slate-500">Check-in readiness</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-950">{next.title}</h2><p className="mt-2 text-sm text-slate-600">{next.location} · {spotsLeft(next)} places remaining</p></div><Link href="/admin/checkin" className="w-fit rounded-lg bg-blue-700 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-800">Open check-in desk</Link></div></section>}<section className="grid gap-4 md:grid-cols-2"><Link href="/admin/events" className="rounded-2xl border border-slate-200 bg-white p-6 hover:border-blue-300"><h2 className="font-display text-xl font-bold text-slate-950">Manage events</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">Review capacity, availability, and what needs a committee decision.</p></Link><Link href="/admin/registrations" className="rounded-2xl border border-slate-200 bg-white p-6 hover:border-blue-300"><h2 className="font-display text-xl font-bold text-slate-950">Review registrations</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">See registrations and waitlists across upcoming events.</p></Link></section></div>;
}
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-3 font-display text-2xl font-bold text-slate-950">{value}</p><p className="mt-2 text-sm text-slate-600">{note}</p></section>; }
